# OCS Operator (Namespace + Operator Group + Subscription)
---
# Create openshift-storage namespace.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
spec: {}
---
# Create Operator Group for OCS Operator.
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-kbd2s
  namespace: openshift-storage
spec:
  targetNamespaces:
  - openshift-storage
---
# Subscribe to OCS Operator.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: "stable-4.9"
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
