apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: dev-fz4wj-storageb
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: dev-fz4wj
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: dev-fz4wj
      machine.openshift.io/cluster-api-machineset: dev-fz4wj-storageb
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: dev-fz4wj
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: dev-fz4wj-storageb
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          cluster.ocs.openshift.io/openshift-storage: ''
      taints:
        - effect: NoSchedule
          key: node.ocs.openshift.io/storage
          value: 'true'
      providerSpec:
        value:
          numCoresPerSocket: 2
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 16384
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: VM Network
          metadata:
            creationTimestamp: null
          numCPUs: 8
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: Datacenter1
            datastore: Vmdata2
            folder: /Datacenter1/vm/dev-fz4wj
            resourcePool: /Datacenter1/host/Storm/Resources
            server: vcenter.k1ckr0cks.local
          template: dev-fz4wj-rhcos
          apiVersion: vsphereprovider.openshift.io/v1beta1